# Form implementation generated from reading ui file 'DiskUI.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(594, 358)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 571, 321))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pixmapLabel = QtWidgets.QLabel(parent=self.layoutWidget)
        self.pixmapLabel.setText("")
        self.pixmapLabel.setObjectName("pixmapLabel")
        self.verticalLayout.addWidget(self.pixmapLabel)
        self.scanButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.scanButton.setObjectName("scanButton")
        self.verticalLayout.addWidget(self.scanButton)
        self.sysInfoButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.sysInfoButton.setObjectName("sysInfoButton")
        self.verticalLayout.addWidget(self.sysInfoButton)
        self.snapshotsButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.snapshotsButton.setObjectName("snapshotsButton")
        self.verticalLayout.addWidget(self.snapshotsButton)
        self.settingsButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.settingsButton.setObjectName("settingsButton")
        self.verticalLayout.addWidget(self.settingsButton)
        self.sourceButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.sourceButton.setObjectName("sourceButton")
        self.verticalLayout.addWidget(self.sourceButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.diskChart = QtWidgets.QWidget(parent=self.layoutWidget)
        self.diskChart.setObjectName("diskChart")
        self.horizontalLayout.addWidget(self.diskChart)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "LMS: Disk Tool"))
        self.scanButton.setText(_translate("MainWindow", "Сканировать"))
        self.sysInfoButton.setText(_translate("MainWindow", "Информация о системе"))
        self.snapshotsButton.setText(_translate("MainWindow", "Посмотреть прошлые снапшоты"))
        self.settingsButton.setText(_translate("MainWindow", "Настройки"))
        self.sourceButton.setText(_translate("MainWindow", "Посмотреть код"))
