# Form implementation generated from reading ui file 'Statistics.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.statisticsTable = QtWidgets.QTableWidget(parent=Form)
        self.statisticsTable.setAlternatingRowColors(True)
        self.statisticsTable.setObjectName("statisticsTable")
        self.statisticsTable.setColumnCount(6)
        self.statisticsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.statisticsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statisticsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statisticsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.statisticsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.statisticsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.statisticsTable.setHorizontalHeaderItem(5, item)
        self.verticalLayout.addWidget(self.statisticsTable)
        self.refreshButton = QtWidgets.QPushButton(parent=Form)
        self.refreshButton.setObjectName("refreshButton")
        self.verticalLayout.addWidget(self.refreshButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Статистика - Топ 10 элементов"))
        self.titleLabel.setText(_translate("Form", "Топ 10 самых больших элементов в базе данных"))
        self.statisticsTable.setSortingEnabled(True)
        item = self.statisticsTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "№"))
        item = self.statisticsTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Путь"))
        item = self.statisticsTable.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Размер (MB)"))
        item = self.statisticsTable.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Размер (GB)"))
        item = self.statisticsTable.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Тип"))
        item = self.statisticsTable.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Снапшот"))
        self.refreshButton.setText(_translate("Form", "Обновить"))
